### ISSUE TITLE
Empty tag: Provides

### ISSUE THREAD

**Issue by xsuchy** [packit/specfile#122]
specfile cannot parse https://src.fedoraproject.org/rpms/mingw-crt/blob/rawhide/f/mingw-crt.spec
It ends up with this TB:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/msuchy/projects/license-validate/./print-spec-changelog.py", line 7, in <module>
    specfile = Specfile(filename)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/specfile.py", line 48, in __init__
    self._spec = RPM.parse(str(self), self.sourcedir, self.macros)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/rpm.py", line 326, in parse
    raise RPMException(stderr=stderr) from e
specfile.exceptions.RPMException: line 71: Empty tag: Provides:
```

**Comment by nforro** [comment]
This is again caused by missing source files (`standard-dlls-mingw32` in this case).

**Comment by nforro** [comment]
What we could theoretically do here is to generate a file containing some sort of a dummy value, but it would have to be a value that's syntactically correct in any place in a spec file, because shell expansions can appear anywhere. Let me think of something.
