### ISSUE TITLE
specfile.exceptions.RPMException: line 8: Illegal char ',' (0x2c) in: Version:        0,0000

### ISSUE THREAD

**Issue by xsuchy** [packit/specfile#124]
Parsing https://src.fedoraproject.org/rpms/perl-Test-Differences/blob/rawhide/f/perl-Test-Differences.spec leads to:
```
Traceback (most recent call last):
  File "/home/msuchy/projects/license-validate/./print-spec-changelog.py", line 7, in <module>
    specfile = Specfile(filename)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/specfile.py", line 48, in __init__
    self._spec = RPM.parse(str(self), self.sourcedir, self.macros)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/rpm.py", line 326, in parse
    raise RPMException(stderr=stderr) from e
specfile.exceptions.RPMException: line 8: Illegal char ',' (0x2c) in: Version:        0,0000
```

**Comment by nforro** [comment]
This is caused by calling locale-dependent printf here: https://src.fedoraproject.org/rpms/perl-Test-Differences/blob/rawhide/f/perl-Test-Differences.spec#_3

With certain locales it uses a wrong decimal separator which makes an invalid version string.

Again, `rpmspec -P perl-Test-Differences.spec` should end with the same error.

**Comment by xsuchy** [comment]
Then we should reset the locale to `C.UTF-8` before calling RPM.parse(). Here is how Mock does that https://github.com/rpm-software-management/mock/commit/24734ef1

**Comment by nforro** [comment]
I don't think it's a good practice for a library to modify the environment.

**Comment by xsuchy** [comment]
The build environment (Mock) does that as a standard thing. It is the other way round, calling rpmbuild directly as a user (with **some** locales and environment variables) is considered and bad practice.

**Comment by xsuchy** [comment]
Just to be sure - I am not asking for resetting the locale to a user. I am asking for changing the locale before calling the parser. And then restore the original values.

**Comment by nforro** [comment]
Mock is not a library though. And specfile doesn't call anything. But point taken, sanitizing the environment before passing control to RPM is probably a good idea.
