### ISSUE TITLE
ValueError: Invalid section name: 'description.'

### ISSUE THREAD

**Issue by xsuchy** [packit/specfile#126]
With the package https://src.fedoraproject.org/rpms/qca-qt4/blob/rawhide/f/qca-qt4.spec
I get:
```
Traceback (most recent call last):
  File "/home/msuchy/projects/license-validate/./print-spec-changelog.py", line 9, in <module>
    with specfile.sections() as sections:
  File "/usr/lib64/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/specfile.py", line 135, in sections
    sections = Sections.parse(lines)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/sections.py", line 199, in parse
    data.append(Section(lines[start][1:], lines[start + 1 : end]))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/sections.py", line 64, in __init__
    raise ValueError(f"Invalid section name: '{name}'")
ValueError: Invalid section name: 'description.'
```
And I am not really sure if this is allowed, but apparently rpmbuild handles this. :shrug:

**Comment by nforro** [comment]
This is clearly a typo in the spec file, but you are right, `rpmspec -P` parses it without issues, so I suppose we should be able to handle it as well.

**Comment by xsuchy** [comment]
This is only one case in whole Fedora. If this would be complicated, I would not mind just proposing a PR for the qca-qt package. It is dirty hack anyway.

**Comment by FrNecas** [comment]
Considering #120 as well doesn't rpm possibly check only for the prefix of section names?

**Comment by FrNecas** [comment]
Hm, I don't really see such behaviour in the rpm source code. This chunk seems to be responsible for matching section names: https://github.com/rpm-software-management/rpm/blob/master/build/parseSpec.c#L87 and according to that, the section name in spec would have to be follow by a space or newline. But I may be missing something

**Comment by nforro** [comment]
> Hm, I don't really see such behaviour in the rpm source code. This chunk seems to be responsible for matching section names: https://github.com/rpm-software-management/rpm/blob/master/build/parseSpec.c#L87 and according to that, the section name in spec would have to be follow by a space or newline. But I may be missing something

It's more likely it is being considered to be a macro expansion/substitution followed by dot, all part of %description section, thus valid.

**Comment by nforro** [comment]
I think we should fix this, because it actually makes sense and we should be consistent with RPM.
