### ISSUE TITLE
Doc - mention the Nikola's video somewhere?

### ISSUE THREAD

**Issue by praiskup** [packit/specfile#128]
https://www.youtube.com/watch?v=yzMfBPdFXZY

**Comment by nforro** [comment]
It's linked from [release notes](https://github.com/packit/specfile/releases/tag/0.8.0) and [changelog](https://github.com/packit/specfile/blob/6b6cbeae4b12458bb7518f889a19371a6d0d7d97/CHANGELOG.md#080), but we could add it to README as well. Or somewhere else?

**Comment by praiskup** [comment]
+1 for the README file

**Comment by TomasTomecek** [comment]
+1 README as well! :)
