### ISSUE TITLE
Implement methods for accessing/modifying Version and Release

### ISSUE THREAD

**Issue by FrNecas** [packit/specfile#14]
https://github.com/packit/specfile#version-and-release

Some inspiration on how macro preserving could work: https://github.com/rebase-helper/rebase-helper/blob/master/rebasehelper/specfile.py#L572 (it definitely has some deficiencies, the code is not very maintainable)

More brainstorming ideas: 
 - preserve_macros could not be just True/False, it could set the level of "automatic guessing" (multi-level) to provide more control

**Comment by nforro** [comment]
Partially implemented in #54.

**Comment by FrNecas** [comment]
This was probably resolved by https://github.com/packit/specfile/pull/101 , right?

**Comment by nforro** [comment]
Yes, it was, closing.
