### ISSUE TITLE
Implement lookaside cache client - downloading and uploading

### ISSUE THREAD

**Issue by nforro** [packit/specfile#15]

**Comment by nforro** [comment]
Should this actually be part of this library? It is a necessary functionality for rebase-helper and packit, yes, but it's not really related to spec files.

**Comment by lachmanfrantisek** [comment]
> Should this actually be part of this library? It is a necessary functionality for rebase-helper and packit, yes, but it's not really related to spec files.

What about creating a subpackage/submodule so we can prepare the shared code and Packit/RebaseHelper part but still be able to exclude it later if we want by just fixing the imports. (=Built it on top of `Specfile`.) It would be really nice to have a different package for this but I am worried it gives us too much maintenance overhead.

But we need to think about this twice. It looks like a precedent for other use cases we will definitely find..;)

--------------

On the other hand (after a while of thinking), it can be really handy to call this code directly from Specfile objects.

e.g. (not sure about the real syntax/types/names..;)

```python
for source in my_specfile.sources:
    if source.is_cached:
        source.upload_to_cache()
    else:
        source.download_from_cache()
```

Or at least make it work with the `Specfile` objects.

e.g. (not sure about the real syntax/types/names..;)

```python
the_lookaside_cache = LookasideCache()

for source in my_specfile.sources:
    if source not in the_lookaside_cache:
        the_lookaside_cache.upload(source)
    else:
        the_lookaside_cache.download(source)
```

**Comment by nforro** [comment]
I think that's a good idea :+1:

**Comment by nforro** [comment]
We decided not to implement this in `specfile` and use `rpkg` for lookaside cache functionality in `rebase-helper` and `packit`.
