### ISSUE TITLE
Implement mid-level manipulation of %prep section

### ISSUE THREAD

**Issue by nforro** [packit/specfile#17]
Necessary functionality:
* Detecting "format" (`%autosetup`, `%setup` + `%autopatch`, `%setup` + `%patch`, something else)
* Adding/removing `%patch` macros
* Parsing macro options

**Comment by TomasTomecek** [comment]
This one is a good test case: https://gitlab.com/redhat/centos-stream/rpms/kernel/-/blob/c9s/kernel.spec#L1296

**Comment by nforro** [comment]
> This one is a good test case: https://gitlab.com/redhat/centos-stream/rpms/kernel/-/blob/c9s/kernel.spec#L1296

That would fall into "something else" category 🙂
It uses `%{patches}`, which is efficienty the same as using `%autosetup`/`%autopatch`, but only for sanity checking.

**Comment by TomasTomecek** [comment]
the main reason I put it here was that I recall some tool in the past couldn't parse kernel's spec, not sure if the was rebase-helper, packit, the python bindings or rpm itself

**Comment by nforro** [comment]
I actually tried to parse `kernel.spec` with this library and it was a success, but that doesn't mean much since quite a lot of required functionality remains to be implemented.
