### ISSUE TITLE
Add script(s) for auto-updating constants from RPM sources

### ISSUE THREAD

**Issue by nforro** [packit/specfile#175]
The number of constants extracted from [RPM sources](https://github.com/rpm-software-management/rpm) in [specfile/constants.py](https://github.com/packit/specfile/blob/0a2b3864294ad3fad9560b8ba881c65c36730301/specfile/constants.py) is getting bigger,  it would be nice to have a script (or a set of scripts) to automatically extract and update the constants every week or so.

**Comment by TomasTomecek** [comment]
...and run it in a github action :)

**Comment by nforro** [comment]
Yes, that's what I had in mind :slightly_smiling_face:

**Comment by majamassarini** [comment]
SPIKE: check how frequently the rpm Sources are changed https://github.com/rpm-software-management/rpm then evaluate if we need to implement a script and how difficult it could be.

**Comment by nforro** [comment]
Here are the constants in question:

* `SECTION_NAMES`
    * 2 changes last year, ~1 change per year between 2014 and 2019
    * represented by `partList` constant array in `build/parseSpec.c`, easy to parse even without parsing C code
*  `TAG_NAMES`, `TAGS_WITH_ARG`
    * 3 changes last year, before that 1 change in 2015 and one in 2017
    * represented by `preambleList` constant array in `build/parsePreamble.c`, easy to parse even without parsing C code
* `ARCH_NAMES`
    * 2 changes last year, 1-2 changes per year before 2020
    * `arch_canon` directives in `rpmrc.in`, easy to parse, it's just a text file
* `SIMPLE_SCRIPT_SECTIONS`, `SCRIPT_SECTIONS`
    * pretty much unchanged
    * deduced from `switch(parsePart)` in `parseSpecSection()` function in `build/parseSpec.c`, tricky to parse
* `SECTION_OPTIONS`
    * no change since 2015
    * multiple sources, mostly `optionsTable` constant array in `build/parse*.c`, easy to parse even without parsing C code

**Comment by nforro** [comment]
I'd say the first 4 constants are candidates for automatic updating, there were multiple new sections and tags introduced last year, even though it's hard to say if the trend will continue.
Either way, having a script that would generate `constants.py` from RPM source code would be really useful in my opinion.
