### ISSUE TITLE
rpm-py-installer deprecation warnings

### ISSUE THREAD

**Issue by gotmax23** [packit/specfile#187]
rpm-py-installer is unable to build wheels and relies on `setup.py install` and eggs. Currently, pip prints obnoxious warnings when the wheel build fails and it falls back to `setup.py install`. This fallback will be removed altogether in pip 23.1. I think it's time to remove this dependency from the pypi package and find another solution. Potential solutions:

1. Keep the dependency. specfile will become uninstallable with newer pip versions.
2. Remove the dependency entirely and advise consumers to use the python3-specfile RPM package or to install python3-rpm and use `pip install --user specfile` or venvs with `--system-site-packages`. `ImportError`s will be raised when `rpm` isn't available.
3. Port the existing rpm-py-installer code (if feasible).
4. Create a new implementation of rpm-py-installer. This could be a shim module that tries to import `rpm` from the system site-packages (a la [pycontribs/selinux](https://github.com/pycontribs/selinux/)).

**Comment by nforro** [comment]
Thanks, yes, this will become an issue (and it already [is](https://github.com/junaruga/rpm-py-installer/issues/260) in certain configurations).

Thanks for laying out the solutions. I'm pretty sure we want to avoid 1, 2 would be an option, but 3 or 4 would be better. I'm afraid that 3 is going to be problematic, so I'm inclined to 4. However, there already is a [dummy RPM package](https://pypi.org/project/rpm/) on PyPI, installation of which always fails, so we would have to replace it.

Let us discuss this within the team.

**Comment by nforro** [comment]
I've opened https://github.com/rpm-software-management/rpm/issues/2360.

**Comment by gotmax23** [comment]
> This could be a shim module that tries to import rpm from the system site-packages

It could be internal to `specfile`.

**Comment by nforro** [comment]
> It could be internal to `specfile`.

I'm not sure how that would/could work. Anyway, it seems we have the green light to take over the dummy RPM package on PyPI and replace it with a shim module, so the next steps would be:

- [ ] Transfer ownership of [rpm project on PyPI](https://pypi.org/project/rpm/) to us
- [ ] Create a GitHub project for the shim module
- [ ] Implement it using https://github.com/pycontribs/selinux as inspiration
- [ ] Replace `rpm-py-installer` dependency with `rpm` in specfile
