### ISSUE TITLE
OOM with 0.13.1 version

### ISSUE THREAD

**Issue by xsuchy** [packit/specfile#196]
I have a script that does:
  ./print-spec-changelog.py rpm-specs/cantor.spec

with version 0.13.1 version this command consumes all swap (it grow to 25GB and then my system become unresponsive). It happens with other spec files, I was just lucky to use 'ps' when the script was processing this one spec file.
It does not happen with 0.12.0 version.

The script is https://pagure.io/copr/license-validate/blob/main/f/print-spec-changelog.py

**Comment by nforro** [comment]
Thank you for reporting this, reproduced. There seems to be some bug in section options processing, let me investigate.
