### ISSUE TITLE
Packit integration test plan doesn't work properly

### ISSUE THREAD

**Issue by nforro** [packit/specfile#211]
packit test suite is fetched from the main branch of packit git repository, but it runs with packit installed from (stable) RPM. That is asking for trouble - for instance a test that doesn't have the corresponding implementation in the stable release yet can be run and fail.

For downstream there is `git_reference.py` script that hardcodes the corresponding git ref to test plans, perhaps we could use something similar here?

**Comment by nforro** [comment]
When the test plan is run from packit, it installs specfile from stable Fedora repos and packit from Copr (so the build matches the git ref - PR source branch):
https://artifacts.dev.testing-farm.io/9a51c79a-65fa-435d-9600-56fa00993b79/work-fulld1z192p8/log.txt

When the test plan is run from specfile, it installs specfile from Copr and packit from stable Fedora repos (now the git ref is `main` and the build is in the best case about a week or two behind):
https://artifacts.dev.testing-farm.io/5b16b3df-e943-49d9-ba20-b0baf429ea71/work-packit-integrationqudqn3ul/log.txt.gz

Possible solutions:
- install packit from [packit-dev](https://copr.fedorainfracloud.org/coprs/packit/packit-dev/) Copr repo
- reference the `stable` branch or the latest tag (or ideally check Bodhi or Fedora repos for the latest update in stable and reference the matching tag)
- something else?

**Comment by FrNecas** [comment]
We build in the `packit-dev` copr repo only when PRs are merged into main, right? In such case, I think that the following content in the plan would make the most sense:

```yaml
discover:
    how: fmf
    url: https://github.com/packit/packit
    filter: tier:0 | tier:1
prepare:
    how: install
    copr: packit/packit-dev

... <adjusts which are already present>
```

This way we are going to test integration against the current main, using the corresponding RPM. I think that we don't even have to specify that `packit` should be installed in `prepare` because this requirement comes from the L1 metadata in packit repo, therefore we just need to enable the copr repo for it. Looks like it works:

```
$ tmt run -a plan -n packit-integration login -s prepare:end
...
    prepare
        how: install
        copr: packit/packit-dev

        how: install
        summary: Install required packages
        name: requires
        package: python3-bodhi-client, python3-flexmock, python3-packit and 15 more

        login: Starting interactive shell
[root@default-0 tree]# packit --version
0.68.0.post17+g21e2863
```

**Comment by nforro** [comment]
@FrNecas It looks like it won't be so simple on EL9: https://artifacts.dev.testing-farm.io/3791393a-97d1-469b-baa9-89b2c3e9e56c/
