### ISSUE TITLE
Document "how to overwrite/undefine macros"

### ISSUE THREAD

**Issue by praiskup** [packit/specfile#243]
### Description

We discussed in a [copr PR](https://github.com/fedora-copr/copr/pull/2769#discussion_r1227680409) there's a way how to override macros, namely:

```
spec = Specfile("python-specfile.spec", macros=[("fedora", "39"), ("rhel", "")])
```

Is this documented somewhere?  Is there a way to "undefine" (e.g. `%rhel` or `%fedora` macro), not replace with an emtpy string?

### Benefit

I checked the README.md, and wasn't able to quickly find this topic. Sorry if I'm just blind.

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by nforro** [comment]
No, unfortunately it's not documented anywhere, except for the docstring.
It's not possible to undefine a macro, but that could be easily implemented.
