### ISSUE TITLE
EPEL-8 build

### ISSUE THREAD

**Issue by praiskup** [packit/specfile#255]
### Description

Seems like there's a very old version 0.7.0 in EPEL8.  The Copr tooling is still supported on EPEL8.
Could we update the package in EPEL8 to v0.20.0?  Seems like we use `%generate_buildrequires`, is there any other principal problem for not doing EPEL8 updates?

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by nforro** [comment]
We have dropped EPEL 8 support a while ago in all packit projects, let me check if we can bring it back in specfile.

**Comment by nforro** [comment]
It would be necessary to revert commit 64b83ddd6012f2d2c1c8ebe39bf0217de73aa54e and do some more fixes, but I think it's doable. However, it would go against https://github.com/packit/packit/issues/1850. Let us discuss this within the team on Thursday.

**Comment by nforro** [comment]
Here is what it would take to re-enable EL 8: https://github.com/packit/specfile/pull/256
