### ISSUE TITLE
Sources in included files are not found

### ISSUE THREAD

**Issue by imphil** [packit/specfile#342]
### What happened? What is the problem?

I have spec files that use "%include" to share common parts, like this (in this case, we have "versioned" packages that are co-installable):

```spec
# my-name-1.0.spec
%global base_name my-name

Version:        1.0
Name:           %{base_name}-%{version}
Release:        1%{?dist}
Source100:      %{base_name}-common.inc

%include %{SOURCE100}
```

```spec
# my-name-common.inc
Source0:        %{base_name}-%{version}.tar.xz
Summary:        My summary
License:        GPLv3
```

I then want to get all sources with `spec.sources().content`

Currently, I only get `["my-name-common.inc"]`. 

https://github.com/packit/specfile/pull/341 has a *failing* test which shows the problem in executable form.

### Workaround

- [ ] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [X] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by nforro** [comment]
Thanks for reporting this. I see the issue, however, I'm not sure if it is possible to do anything about it. specfile won't be able to edit tags in included files, but I suppose you are interested only in parsing/read-only access, right? If so, I think you should be able to get what you want like this:

```python
from specfile import Specfile
from specfile.sources import Sources

spec = Specfile(...)
for source in Sources(spec.tags(spec.parsed_sections.package).content, []):
    print(source.expanded_location)
```

**Comment by imphil** [comment]
Thanks @nforro, that does the trick! I'm indeed only interested in the parsing part.

Just FYI, since I had both code paths around: specfile is around 5x slower than `rpmspec -P` and parsing the `Source` lines from the output. It's not much of a problem for my use case, but maybe good to know.
