### ISSUE TITLE
Fails to parse NetworkManager.spec

### ISSUE THREAD

**Issue by bilelmoussaoui** [packit/specfile#403]
### What happened? What is the problem?

Trying to create an instance of `Specfile` of `NetworkManager.spec` fails with the following

```
    with spec_file.sources() as sources:
         ^^^^^^^^^^^^^^^^^^^
  File "/some-path/.venv/lib/python3.12/site-packages/specfile/context_management.py", line 133, in __call__
    self.values[key] = next(self.generators[key])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some-path/.venv/lib/python3.12/site-packages/specfile/specfile.py", line 365, in sources
    with self.sections() as sections, self.tags() as tags:
                                      ^^^^^^^^^^^
  File /some-path//.venv/lib/python3.12/site-packages/specfile/context_management.py", line 133, in __call__
    self.values[key] = next(self.generators[key])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some-path/.venv/lib/python3.12/site-packages/specfile/specfile.py", line 292, in tags
    tags = Tags.parse(section, context=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some-path/.venv/lib/python3.12/site-packages/specfile/tags.py", line 497, in parse
    lines = process_conditions(list(section), macro_definitions, context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some-path/.venv/lib/python3.12/site-packages/specfile/conditions.py", line 133, in process_conditions
    result.append((line, branches[-2]))
                         ~~~~~~~~^^^^
```

### What did you expect to happen?

The parsing to pass

### Steps to reproduce

```bash
1.
2.
3.
```

### Workaround

- [ ] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [x] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by lachmanfrantisek** [comment]
Hi @bilelmoussaoui !

Just to be sure, we are speaking about this specfile, right?
https://src.fedoraproject.org/rpms/NetworkManager/blob/rawhide/f/NetworkManager.spec

I guess you use a fresh version of specfile.

@nforro do you have any quick ideas what could go wrong here?

**Comment by bilelmoussaoui** [comment]
I am using the spec file from `NetworkManager-1.48.2-2.el9` as I am trying to make use it for some internal experiment.

**Comment by nforro** [comment]
> @nforro do you have any quick ideas what could go wrong here?

Yes, I've already fixed it but discovered another bug during that, so it will take a bit more time :slightly_smiling_face:

**Comment by bilelmoussaoui** [comment]
Thanks a lot @nforro
