### ISSUE TITLE
RPM python bindings dependency

### ISSUE THREAD

**Issue by nforro** [packit/specfile#72]
`specfile` currently [depends](https://github.com/packit/specfile/blob/21af272b7664204fa0d93ae5e3cab129757e54bd/setup.cfg#L38) on `rpm` which is not (and probably never will be) available on PyPI. That means whoever wants to install it using `pip` has to have RPM python bindings already installed (usually via a package manager).
We could instead depend on [rpm-py-installer](https://github.com/junaruga/rpm-py-installer), but it's not a flawless solution.

**Comment by nforro** [comment]
One problem is, specifying `rpm-py-installer` as a dependency breaks dynamic buildrequires, because there is no `python3dist(rpm-py-installer)` in Fedora.

A solution that comes to mind is to continue depending on `rpm` and use an extra for `rpm-py-installer`, so users could install `specfile` with `pip install specfile[rpm-py-installer]` (or something similar).

**Comment by TomasTomecek** [comment]
how hard would it be to have rpm available on PyPI?

would it be too complicated to write a script and run it in GitHub action that would take care of that?

**Comment by nforro** [comment]
> would it be too complicated to write a script and run it in GitHub action that would take care of that?

What do you mean exactly? I don't follow.

**Comment by TomasTomecek** [comment]
So, I understand that rpm-py-installer compiles the rpm python bindings locally on the fly. That's great but requires all build tools and everything.

Since you can have binary artifacts on PyPI, one could do that in a controlled environment (e.g. GitHub action) and upload the artifacts to PyPI as bdist_wheel.

Do you think that would work?

**Comment by nforro** [comment]
I'm not sure. The thing is, RPM python bindings are tied to a specific RPM version. So there would have to be a build for every RPM version ever released and the correct one would have to be chosen during installation.

If I understand it correctly, `rpm-py-installer` first tries to install matching bindings from a system package, and only if that's not possible it builds them from source (and in the worst case it builds RPM itself from source as well).

**Comment by nforro** [comment]
See also https://github.com/rpm-software-management/rpm/issues/273

**Comment by TomasTomecek** [comment]
oh, didn't realize it works like that, thank you for educating me

I wish they changed their mind.

**Comment by nforro** [comment]
A better solution that works with dynamic buildrequires is to substitute `rpm-py-installer` with `rpm` in `setup.cfg` in `%prep` (that works because `%prep` is executed before `%generate_buildrequires`):

```specfile
%prep
%autosetup -p1 -n specfile-%{version}
sed -i 's/rpm-py-installer/rpm/' setup.cfg

%generate_buildrequires
%pyproject_buildrequires -x testing
```
